
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aluno
 */
public class BemVindo extends javax.swing.JFrame {
    Calendar c = Calendar.getInstance();
    public BemVindo() {
        initComponents();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lhora = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        bomdia = new javax.swing.JLabel();
        ola = new javax.swing.JLabel();
        hello = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 153, 204));
        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 204));
        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 100, 30));

        lhora.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lhora.setForeground(new java.awt.Color(153, 0, 153));
        lhora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 70, 30));

        data.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        data.setForeground(new java.awt.Color(153, 0, 153));
        data.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 100, 30));

        bomdia.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        bomdia.setForeground(new java.awt.Color(204, 153, 255));
        bomdia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(bomdia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 290, 70));

        ola.setFont(new java.awt.Font("Perpetua Titling MT", 0, 36)); // NOI18N
        ola.setForeground(new java.awt.Color(0, 153, 153));
        ola.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ola, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 610, 90));

        hello.setIcon(new javax.swing.ImageIcon("C:\\Users\\IGOR\\Desktop\\Sarah\\SARAH IFBA\\SBC Saúde (1).png")); // NOI18N
        hello.setText("jLabel1");
        getContentPane().add(hello, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       Date dataSistema = new Date();
       SimpleDateFormat formato = new SimpleDateFormat ("dd/MM/yyyy");
       data.setText(formato.format(dataSistema));
       
       Timer timer = new Timer (1000, new hora());
       timer.start();
       
       int hora = c.get(Calendar.HOUR_OF_DAY);
        if (hora >= 6 && hora < 12) {
            bomdia.setText("Bom dia!");        
        } else if (hora >= 12 && hora < 18) {
            bomdia.setText("Boa tarde!");
        } else {
            bomdia.setText("Boa noite!");
        }
        
        ola.setText("Seja bem vindo(a) de volta!");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BemVindo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BemVindo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BemVindo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BemVindo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BemVindo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bomdia;
    private javax.swing.JLabel data;
    private javax.swing.JLabel hello;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lhora;
    private javax.swing.JLabel ola;
    // End of variables declaration//GEN-END:variables
    class hora implements ActionListener {
     @Override
     public void actionPerformed (ActionEvent e){
    Calendar now = Calendar.getInstance();
    lhora.setText(String.format("%1$tH:%1$tM:%1$tS",now));
}
}
}

