
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aluno
 */
public class TelaResponsaveis extends javax.swing.JFrame {

    /**
     * Creates new form TelaResponsaveis
     */
    String nome;
    public TelaResponsaveis(String nomeu) {
         Date dataNascimento = null;
    int idade;
        initComponents();
        nome = nomeu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeresp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        datanr = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rgr = new javax.swing.JFormattedTextField();
        cpfr = new javax.swing.JFormattedTextField();
        sair = new javax.swing.JButton();
        prox = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("DADOS DO RESPONSÁVEL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Nome completo: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        nomeresp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomerespFocusLost(evt);
            }
        });
        getContentPane().add(nomeresp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 380, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Data de Nascimento:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        try {
            datanr.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        datanr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datanrActionPerformed(evt);
            }
        });
        getContentPane().add(datanr, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 110, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("RG:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("CPF:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        try {
            rgr.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        rgr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                rgrFocusLost(evt);
            }
        });
        getContentPane().add(rgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 240, 30));

        try {
            cpfr.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpfrFocusLost(evt);
            }
        });
        getContentPane().add(cpfr, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 260, 30));

        sair.setBackground(new java.awt.Color(255, 204, 204));
        sair.setForeground(new java.awt.Color(153, 0, 153));
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 80, -1));

        prox.setBackground(new java.awt.Color(204, 204, 255));
        prox.setForeground(new java.awt.Color(0, 102, 102));
        prox.setText("Próximo >");
        prox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proxActionPerformed(evt);
            }
        });
        getContentPane().add(prox, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 480, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\IGOR\\Desktop\\Sarah\\SARAH IFBA\\SBC Saúde (1).png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void proxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxActionPerformed
        if(nomeresp.getText().equals("")){
             JOptionPane.showMessageDialog(null,"Preencha o nome completo. ", "Aviso", JOptionPane.WARNING_MESSAGE);
             return;
         }
        if(datanr.getText().equals("  /  /    ")){
             JOptionPane.showMessageDialog(null,"Preencha a data de nascimento. ", "Aviso", JOptionPane.WARNING_MESSAGE);
             return;
         }
        if(rgr.getText().equals("  .   .   -  ")){
             JOptionPane.showMessageDialog(null,"Preencha o RG. ", "Aviso", JOptionPane.WARNING_MESSAGE);
             return;
        }
             if(cpfr.getText().equals("   .   .   -  ")){
             JOptionPane.showMessageDialog(null,"Preencha o CPF. ", "Aviso", JOptionPane.WARNING_MESSAGE);
             return;
             }
        else{
           new TelaCad(nome).setVisible(true);
                }
    }//GEN-LAST:event_proxActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
    System.exit(0);         
    }//GEN-LAST:event_sairActionPerformed

    private void datanrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datanrActionPerformed
    SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy");
        formatoData.setLenient(false);
        try {
        Date dataNascimento = formatoData.parse(datanr.getText());
           
        } catch (Exception e) {
            System.out.println("Data Inválida!");
        }        

    }//GEN-LAST:event_datanrActionPerformed

    private void nomerespFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomerespFocusLost
       
    }//GEN-LAST:event_nomerespFocusLost

    private void rgrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rgrFocusLost
        if(rgr.getText().isEmpty()){
              JOptionPane.showMessageDialog(null,"Preencha o RG."); 
          }
    }//GEN-LAST:event_rgrFocusLost

    private void cpfrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfrFocusLost
       
    }//GEN-LAST:event_cpfrFocusLost

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaResponsaveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaResponsaveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaResponsaveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaResponsaveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField cpfr;
    private javax.swing.JFormattedTextField datanr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nomeresp;
    private javax.swing.JButton prox;
    private javax.swing.JFormattedTextField rgr;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
