
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aluno
 */
public class Usuariosbc extends javax.swing.JFrame {
    Date dataNascimento = null;
    int idade;
    /**
     * Creates new form Usuariosbc
     */
    public Usuariosbc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        datanu = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cpfu = new javax.swing.JFormattedTextField();
        rgu = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        proximo = new javax.swing.JButton();
        estado = new javax.swing.JTextField();
        endereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        imagemsbc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeuFocusLost(evt);
            }
        });
        nomeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeuActionPerformed(evt);
            }
        });
        getContentPane().add(nomeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 350, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 204));
        jLabel1.setText("DADOS PESSOAIS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nome completo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Data de nascimento: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        try {
            datanu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        datanu.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        datanu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                datanuFocusLost(evt);
            }
        });
        datanu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datanuActionPerformed(evt);
            }
        });
        getContentPane().add(datanu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 100, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("CPF:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("RG:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        try {
            cpfu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpfuFocusLost(evt);
            }
        });
        cpfu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfuActionPerformed(evt);
            }
        });
        getContentPane().add(cpfu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 290, 30));

        try {
            rgu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        rgu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                rguFocusLost(evt);
            }
        });
        rgu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rguActionPerformed(evt);
            }
        });
        getContentPane().add(rgu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 300, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Estado:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Endereço:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        exit.setBackground(new java.awt.Color(255, 204, 255));
        exit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        exit.setForeground(new java.awt.Color(153, 0, 0));
        exit.setText("Sair");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, 60, -1));

        proximo.setBackground(new java.awt.Color(204, 204, 255));
        proximo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        proximo.setForeground(new java.awt.Color(0, 102, 102));
        proximo.setText("Próximo >");
        proximo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                proximoFocusLost(evt);
            }
        });
        proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoActionPerformed(evt);
            }
        });
        getContentPane().add(proximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 520, 110, -1));

        estado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                estadoFocusLost(evt);
            }
        });
        estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoActionPerformed(evt);
            }
        });
        getContentPane().add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 160, -1));

        endereco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                enderecoFocusLost(evt);
            }
        });
        endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoActionPerformed(evt);
            }
        });
        getContentPane().add(endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 310, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("*Este serviço está disponível apenas no Brasil");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 2, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("*Cidade, rua, bairro, complemento, n°");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        imagemsbc.setIcon(new javax.swing.ImageIcon("C:\\Users\\IGOR\\Desktop\\Sarah\\SARAH IFBA\\SBC Saúde (1).png")); // NOI18N
        getContentPane().add(imagemsbc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 556));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoActionPerformed

    private void nomeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeuActionPerformed
       
    }//GEN-LAST:event_nomeuActionPerformed

    private void datanuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datanuActionPerformed
        
    }//GEN-LAST:event_datanuActionPerformed

    private void proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoActionPerformed
      
       
              if(nomeu.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Preencha o nome completo.");
        }
             if(cpfu.getText().equals("   .   .   -  ")){
             JOptionPane.showMessageDialog(null,"Preencha o CPF. ", "Aviso", JOptionPane.WARNING_MESSAGE);
             return;
         }
              if(rgu.getText().equals("  .   .   -  ")){
             JOptionPane.showMessageDialog(null,"Preencha o RG. ", "Aviso", JOptionPane.WARNING_MESSAGE);
             return;
         }
              if(estado.getText().isEmpty()){
             JOptionPane.showMessageDialog(null,"Preencha o Estado.");
         }
              if(endereco.getText().isEmpty()){
              JOptionPane.showMessageDialog(null,"Preencha o endereço."); 
          }
              else{
                  if (idade <  18) {
            new TelaResponsaveis(nomeu.getText()).setVisible(true);
       } else {
           new TelaCad(nomeu.getText()).setVisible(true); 
        } 
              }
              
    }//GEN-LAST:event_proximoActionPerformed
    int calcularIdade(Date dataNascimento) {
        Calendar dataNasc = Calendar.getInstance();
        dataNasc.setTime(dataNascimento);

        Calendar hoje = Calendar.getInstance();
        hoje.getTime();

        int idade = hoje.get(Calendar.YEAR) - dataNasc.get(Calendar.YEAR);

        dataNasc.add(Calendar.YEAR, idade);

        if (hoje.before(dataNasc)) {
            idade--;
        }

        return idade;

    }
    private void datanuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_datanuFocusLost
       
        
        SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy");
        formatoData.setLenient(false);
        try {
            dataNascimento = formatoData.parse(datanu.getText());
            idade = calcularIdade(dataNascimento);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Inválida!");
        }
    }//GEN-LAST:event_datanuFocusLost

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void cpfuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfuActionPerformed
        
    }//GEN-LAST:event_cpfuActionPerformed

    private void rguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rguActionPerformed
        
    }//GEN-LAST:event_rguActionPerformed

    private void estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoActionPerformed
        
    }//GEN-LAST:event_estadoActionPerformed

    private void nomeuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeuFocusLost
       
    }//GEN-LAST:event_nomeuFocusLost

    private void cpfuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfuFocusLost
       
    }//GEN-LAST:event_cpfuFocusLost

    private void rguFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rguFocusLost
        
    }//GEN-LAST:event_rguFocusLost

    private void estadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_estadoFocusLost
       if(estado.getText().isEmpty()){
             JOptionPane.showMessageDialog(null,"Preencha o Estado.");
         }
    }//GEN-LAST:event_estadoFocusLost

    private void enderecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enderecoFocusLost
       
         
    }//GEN-LAST:event_enderecoFocusLost

    private void proximoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_proximoFocusLost

    }//GEN-LAST:event_proximoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuariosbc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuariosbc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuariosbc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuariosbc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuariosbc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField cpfu;
    private javax.swing.JFormattedTextField datanu;
    private javax.swing.JTextField endereco;
    private javax.swing.JTextField estado;
    private javax.swing.JButton exit;
    private javax.swing.JLabel imagemsbc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nomeu;
    private javax.swing.JButton proximo;
    private javax.swing.JFormattedTextField rgu;
    // End of variables declaration//GEN-END:variables
}
